update to 1.0RC5

diff --git a/packages/setup/scripts/install-drivers b/packages/setup/scripts/install-drivers
--- a/packages/setup/scripts/install-drivers
+++ b/packages/setup/scripts/install-drivers
@@ -39,7 +39,7 @@ blacklist nouveau
 # Disable NVIDIA binary driver
 #blacklist nvidia
 
-options uvesafb mode_option=1360x768-32 scroll=ywrap
+options uvesafb mode_option=1024x768-16 scroll=ywrap
 _EOF
       echo "uvesafb" > /usr/lib/modules-load.d/uvesafb.conf
    fi
@@ -134,14 +134,15 @@ else
 fi
 
 dialog --clear --title "$(gettext "Install additional DVB driver")" --menu \
-"$(gettext "Before proceeding please confirm your DVB device specific information. Choose the driver you need to install carefully.")" 14 80 7 \
+"$(gettext "Before proceeding please confirm your DVB device specific information. Choose the driver you need to install carefully.")" 16 80 8 \
  "Exit" "$(gettext "I do not want to install now.")" \
  "s2-liplianin" "$(gettext "Support most of the devices,such as DVBWorld,Tevii,Prof...")" \
  "tbs-drivers" "$(gettext "Support all the TBS devices")" \
  "dvbsky-drivers" "$(gettext "Support all the DVBSky devices")" \
  "tbs-dvbc-drivers" "$(gettext "Support all the TBS DVB-C devices")" \
+ "tbs-atsc-drivers" "$(gettext "Support all the TBS ATSC devices")" \
  "dvbsky-dvbc-drivers" "$(gettext "Support all the DVBSky DVB-C devices")" \
- "tbs-qbox-drivers" "$(gettext "Support the TBS QBOX I DVB-C devices")" 2> /tmp/driver.tmp
+ "tbs-qbox-drivers" "$(gettext "Support the TBS QBOX I DVB-S2 devices")" 2> /tmp/driver.tmp
 
 case "$(cat /tmp/driver.tmp)" in
   s2-liplianin)	tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
@@ -169,6 +170,13 @@ case "$(cat /tmp/driver.tmp)" in
                 opkg install http://sourceforge.net/projects/openpctv/files/packages/tbs-dvbc-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download tbs-dvbc-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
 		[ -f /usr/bin/enigma2.tbs ] && (rm /usr/bin/enigma2; ln -sf /usr/bin/enigma2.tbs /usr/bin/enigma2)
 		HAS_INSTALLED=yes
+                ;;
+  tbs-atsc-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
+                rm -rf /lib/modules/$kernelver/kernel/drivers/media
+                echo "Download and install tbs-atsc-drivers-${kernelver}_Last_${machine}.opk, please wait..."
+                opkg install http://sourceforge.net/projects/openpctv/files/packages/tbs-atsc-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download tbs-atsc-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
+                [ -f /usr/bin/enigma2.tbs ] && (rm /usr/bin/enigma2; ln -sf /usr/bin/enigma2.tbs /usr/bin/enigma2)
+                HAS_INSTALLED=yes
                 ;;
   tbs-qbox-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
                 rm -rf /lib/modules/$kernelver/kernel/drivers/media
