update to devel-20140624

diff --git a/packages/setup/scripts/install-drivers b/packages/setup/scripts/install-drivers
--- a/packages/setup/scripts/install-drivers
+++ b/packages/setup/scripts/install-drivers
@@ -7,10 +7,55 @@ export TEXTDOMAIN=openpctv
 . /etc/lsb-release
 [ -z ${DISTRIB_ID} ] && DISTRIB_ID=OpenPCTV
 
+kernelver=$(uname -r)
+if [[ "$(uname -m)" == *86 ]]; then
+  machine=i586
+else
+  machine=i586
+fi
+
 finishinstall () {
 dialog --title "$(gettext "Reboot") ${DISTRIB_ID}?" --clear --yesno "$(gettext "Driver package has been installed successfully. Now you have to reboot to verify whether the driver works.")" 8 61
 retval=$?
 [ $retval -eq 0 ] && reboot
+}
+
+selectnvidia () {
+dialog --clear --title "$(gettext "Select NVIDIA graphics driver")" --menu \
+"$(gettext "Both nouveau and nvidia enable VDPAU driver support for hardware-accelerated video decoding. By default we use the nouveau driver, you can also use the nvidia driver to get better support.")" 12 80 3 \
+ "nouveau" "$(gettext "Open-source NVIDIA graphics driver")" \
+ "nvidia" "$(gettext "NVIDIA's binary Linux graphics driver")" 2> /tmp/driver_nvidia.tmp
+
+if [ $(cat /tmp/driver_nvidia.tmp) = "nvidia" -a ${CURRENT_DRV} = "nouveau" ]; then
+   echo "Download and install xf86-video-nvidia-\${kernelver}_Last_\${machine}.opk, please wait..."
+   opkg install http://sourceforge.net/projects/openpctv/files/packages/xf86-video-nvidia-${kernelver}_Last_${machine}.opk/download || (echo "Can't download xf86-video-nvidia-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
+   HAS_INSTALLED=yes
+elif [ $(cat /tmp/driver_nvidia.tmp) = "nouveau" -a ${CURRENT_DRV} = "nvidia" ]; then
+   opkg remove xf86-video-nvidia
+fi
+rm /tmp/driver*.tmp
+}
+
+checknvidia () {
+for i in 10 9 8 7 6 5 4 3 2 1; do
+   if [ -f /sys/class/drm/card0/device/vendor ]; then
+      break
+   else
+      sleep 0.1
+   fi
+done
+
+if [ $(cat /sys/class/drm/card0/device/vendor) = "0x10de" ]; then
+  lsmod > /tmp/lsmod.tmp
+  if grep -q -i nvidia /tmp/lsmod.tmp; then
+    CURRENT_DRV=nvidia
+  elif grep -q -i nouveau /tmp/lsmod.tmp; then
+    CURRENT_DRV=nouveau
+  fi
+  selectnvidia
+fi
+[ X${HAS_INSTALLED} = "Xyes" ] && finishinstall
+exit
 }
 
 commit () {
@@ -59,12 +104,12 @@ if [ -c /dev/dvb/adapter[0..9]/dvr[0...9] -a -c /dev/dvb/adapter[0..9]/frontend[
   dialog --title "$(gettext "Additional DVB driver")" --clear --defaultno \
   --yesno "$(gettext "Your DVB devices seem to be normal. Perhaps you do not need to install other additional drivers. If you want to install additional drivers please select 'Yes'")" 8 61
   retval=$?
-  [ $retval -eq 1 ] && exit
+  [ $retval -eq 1 ] && checknvidia
 else
   dialog --title "$(gettext "Additional DVB driver")" --clear \
   --yesno "$(gettext "Your DVB device does not seem to work properly. Perhaps you should install another driver. Do you want to install the additional drivers?")" 8 61
   retval=$?
-  [ $retval -eq 1 ] && exit
+  [ $retval -eq 1 ] && checknvidia
 fi
 
 dialog --clear --title "$(gettext "Install additional DVB driver")" --menu \
@@ -76,52 +121,47 @@ dialog --clear --title "$(gettext "Install additional DVB driver")" --menu \
  "tbs-dvbc-drivers" "$(gettext "Support all the TBS DVB-C devices")" \
  "dvbsky-dvbc-drivers" "$(gettext "Support all the DVBSky DVB-C devices")" \
  "tbs-qbox-drivers" "$(gettext "Support the TBS QBOX I DVB-C devices")" 2> /tmp/driver.tmp
-kernelver=$(uname -r)
-if [[ "$(uname -m)" == *86 ]]; then
-  machine=i586
-else
-  machine=i586
-fi
+
 case "$(cat /tmp/driver.tmp)" in
-  Exit)		exit
-		;;
   s2-liplianin)	tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
 		rm -rf /lib/modules/$kernelver/kernel/drivers/media
 		echo "Download and install s2-liplianin-\${kernelver}_Last_\${machine}.opk, please wait..."
 		opkg install http://sourceforge.net/projects/openpctv/files/packages/s2-liplianin-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download s2-liplianin-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
-		finishinstall
+		HAS_INSTALLED=yes
 		;;
   tbs-drivers)	tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
 		rm -rf /lib/modules/$kernelver/kernel/drivers/media
 		echo "Download and install tbs-drivers-${kernelver}_Last_${machine}.opk, please wait..."
 		opkg install http://sourceforge.net/projects/openpctv/files/packages/tbs-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download tbs-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
 		[ -f /usr/bin/enigma2.tbs ] && (rm /usr/bin/enigma2; ln -sf /usr/bin/enigma2.tbs /usr/bin/enigma2)
-		finishinstall
+		HAS_INSTALLED=yes
 		;;
   dvbsky-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
                 rm -rf /lib/modules/$kernelver/kernel/drivers/media
                 echo "Download and install dvbsky-drivers-${kernelver}_Last_${machine}.opk, please wait..."
                 opkg install http://sourceforge.net/projects/openpctv/files/packages/dvbsky-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download dvbsky-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
-                finishinstall
+		HAS_INSTALLED=yes
                 ;;
   tbs-dvbc-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
                 rm -rf /lib/modules/$kernelver/kernel/drivers/media
                 echo "Download and install tbs-dvbc-drivers-${kernelver}_Last_${machine}.opk, please wait..."
                 opkg install http://sourceforge.net/projects/openpctv/files/packages/tbs-dvbc-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download tbs-dvbc-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
 		[ -f /usr/bin/enigma2.tbs ] && (rm /usr/bin/enigma2; ln -sf /usr/bin/enigma2.tbs /usr/bin/enigma2)
-                finishinstall
+		HAS_INSTALLED=yes
                 ;;
   tbs-qbox-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
                 rm -rf /lib/modules/$kernelver/kernel/drivers/media
                 echo "Download and install tbs-qbox-drivers-${kernelver}_Last_${machine}.opk, please wait..."
                 opkg install http://sourceforge.net/projects/openpctv/files/packages/tbs-qbox-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download tbs-qbox-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
                 [ -f /usr/bin/enigma2.tbs ] && (rm /usr/bin/enigma2; ln -sf /usr/bin/enigma2.tbs /usr/bin/enigma2)
-                finishinstall
+		HAS_INSTALLED=yes
                 ;;
   dvbsky-dvbc-drivers)  tar -czf /root/kernel_media_$(date +%Y%m%d%H%M%S)_backup.tgz /lib/modules/$kernelver/kernel/drivers/media
                 rm -rf /lib/modules/$kernelver/kernel/drivers/media
                 echo "Download and install dvbsky-dvbc-drivers-${kernelver}_Last_${machine}.opk, please wait..."
                 opkg install http://sourceforge.net/projects/openpctv/files/packages/dvbsky-dvbc-drivers-${kernelver}_Last_${machine}.opk/download --force-overwrite || (echo "Can't download dvbsky-dvbc-drivers-${kernelver}_Last_${machine}.opk, check your network settings."; exit)
-                finishinstall
+		HAS_INSTALLED=yes
                 ;;
 esac
+
+checknvidia
